# Generated by Django 2.1.7 on 2019-03-19 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xuexi', '0002_auto_20190319_1055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='testUser',
        ),
        migrations.AlterModelTable(
            name='testuser',
            table=None,
        ),
    ]
