# Generated by Django 2.1.7 on 2019-03-15 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='biaoqian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='fenlei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='姓名')),
                ('wangming', models.CharField(max_length=200, verbose_name='网名')),
                ('zhiye', models.CharField(max_length=200, verbose_name='职业')),
                ('address', models.CharField(max_length=500, verbose_name='地址')),
                ('email', models.EmailField(max_length=200, verbose_name='邮箱')),
                ('qq', models.IntegerField(default=1)),
                ('weixin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='wenzhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('neirong', models.TextField()),
                ('img', models.ImageField(upload_to='img', verbose_name='图片路径')),
                ('dianji', models.IntegerField(default=1)),
                ('zhiding', models.BooleanField(default=False)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('biaoqian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biaoqian', to='boke.biaoqian')),
                ('fenlei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fenlei', to='boke.fenlei')),
                ('uesr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='boke.user')),
            ],
        ),
    ]
