# Generated by Django 2.1.7 on 2019-03-18 04:07

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('boke', '0003_auto_20190315_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biaoqian',
            options={'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='fenlei',
            options={'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='wenzhang',
            options={'verbose_name_plural': '文章'},
        ),
        migrations.AlterField(
            model_name='biaoqian',
            name='name',
            field=models.CharField(max_length=200, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='fenlei',
            name='name',
            field=models.CharField(max_length=200, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.IntegerField(default=1, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weixin',
            field=models.CharField(max_length=200, verbose_name='微信'),
        ),
        migrations.AlterField(
            model_name='wenzhang',
            name='biaoqian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biaoqian', to='boke.biaoqian', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='wenzhang',
            name='dianji',
            field=models.IntegerField(default=1, verbose_name='点击量'),
        ),
        migrations.AlterField(
            model_name='wenzhang',
            name='fenlei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fenlei', to='boke.fenlei', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='wenzhang',
            name='insert_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='wenzhang',
            name='neirong',
            field=tinymce.models.HTMLField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='wenzhang',
            name='title',
            field=models.CharField(max_length=500, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='wenzhang',
            name='uesr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='boke.user', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='wenzhang',
            name='zhiding',
            field=models.BooleanField(default=False, verbose_name='推荐'),
        ),
    ]
