# Generated by Django 2.1.7 on 2019-03-20 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceshi1', '0002_auto_20190320_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='page',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=10), django.core.validators.MinValueValidator(limit_value=3)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('1[345678]\\d{9}', message='请输入正确的手机号码')]),
        ),
    ]
