# Generated by Django 2.1.7 on 2019-03-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceshi1', '0004_auto_20190320_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='file/%Y%s%d')),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
