# Generated by Django 2.1.7 on 2019-03-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceshi1', '0005_auto_20190321_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodel',
            name='file',
            field=models.FileField(upload_to='file/%Y%m%d'),
        ),
    ]
