# Generated by Django 2.1.7 on 2019-03-21 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceshi1', '0007_uploadmodel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='img',
        ),
    ]
